### ISSUE TITLE
dl des album entier

### ISSUE THREAD

**Issue by lolio-dev** [Darkempire78/DeezerDownloader-Discord-Bot#2]
Salut, le but est génial et super pratique mais ce serait sympa de pouvoir dl des albums d'un coup au lieu de télecharger chaque musique 1 a 1.

**Comment by Darkempire78** [comment]
Hey lolio-dev ! En effet la possibilité de télécharger des albums entiers pourrait être pratique. Tout dépend de l'utilisation souhaité, mais cette option n'a pas était ajouté dans le but de ne pas surcharger le bot. Cependant, il est possible que certaines personnes souhaitent pouvoir télécharger des albums entiers. Pour le moment étant en vacances je ne peux pas ajouter cette possibilité, mais si l'envie de créer cette commande en attendant, ce serait avec joie :) 
Je doute que ce soit très dur a implémenter.

**Comment by lolio-dev** [comment]
heu ouais, je vais essayé de faire ça mais je ne garanti pas que j'y arriverai je ne connais rien en bot discord

**Comment by Darkempire78** [comment]
Et bien voilà la nouvelle commande permettant de download un album en entier :D
