### ISSUE TITLE
bug d'envoi de message

### ISSUE THREAD

**Issue by lolio-dev** [Darkempire78/DeezerDownloader-Discord-Bot#3]
salut, juste pour te dire que quand on veux dl un album il envoie les messages en double 
![image](https://user-images.githubusercontent.com/58036293/90319927-c38c3900-df3c-11ea-8326-42b082db0935.png)

**Comment by Darkempire78** [comment]
Si on regarde bien le screenshot, il y a deux bots (voir les noms différents)

**Comment by lolio-dev** [comment]
Ah oui fuck j'avais pas fait le rapprochement, dsl pour le dérangement

**Comment by Darkempire78** [comment]
Pas de soucis !
